# This is a basic workflow to help you get started with Actions

name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: don2vito/metrics@master
        with:
          # Your GitHub token
          token: ${{902fad7112428ef65137d4185e705c96665f330d}}
