
生成 Github actions 代码

生成 README.md 代码
3.3 配置 README.md
将代码贴入 「README.md」
![Metrics](https://metrics.lecoq.io/don2vito?template=classic&isocalendar=1&languages=1&people=1&activity=1&isocalendar.duration=full-year&languages.colors=github&languages.threshold=0%25&people.limit=28&people.size=28&people.types=followers%2C%20following&people.identicons=false&people.shuffle=false&activity.limit=5&activity.days=14&activity.filter=all&activity.visibility=all&activity.timestamps=false&config.timezone=Asia%2FShanghai)
3.4 配置 Github Actions 自动化脚本（action.yml）
进入仓库中的 「Actions」 ，选择 「New workflow」

将代码贴入 「action.yml」，「默认每间隔 1 小时自动运行一次」，在 Github 服务器上的 Ubantu 系统运行
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.MY_HOME }}

          # Options
          user: don2vito
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following
